### ISSUE TITLE
Logging statement with format string on new line not found

### ISSUE THREAD

**Issue by ArrowAcrobatics** [crownstone/bluenet-lib-logs#1]
The following statement yields the error `Can't find log format in: isation/cs_TrackableParser.cpp:251 	LOGTrackableParserDebug(`

```	LOGTrackableParserDebug(
			"start %d, chunksize %d, total size %d",
			cmd_data->chunkStartIndex,
			cmd_data->chunkSize,
			cmd_data->totalSize);
```

Temporary workaround: keep format string on same line as log (macro)function name.
Full fix: adjust regex to scan for format string on subsequent line.

**Comment by mrquincle** [comment]
Is it possible to leverage the (pre)compiler to get these statements out? They are very good in parsing code.

**Comment by vliedel** [comment]
Should be fixed with https://github.com/crownstone/bluenet-lib-logs/commit/7da8000a8bbebb5731ae5563eeb359cd15d78a72
